### ISSUE TITLE
Autenticação do cliente

### ISSUE THREAD

**Issue by mfornaciari** [TreinaDev/e-commerce-td08-time02#11]
Um cliente deve poder se autenticar na plataforma.

Um cliente deve ter:
nome, code(cnpj ou cpf), senha, email.

**Comment by muckagr** [comment]
Tela de login do cliente:


![Image](https://user-images.githubusercontent.com/19896068/173915878-1dfe956d-205e-4c78-9482-579a4a1a7708.png)
